'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Abilities

    '''<summary>
    '''ddlStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStr As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStrTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStrTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblStrTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStrTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDex As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDex control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDex As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDexTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDexTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDexTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDexTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCon As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCon control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCon As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtConTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlInt As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblInt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtIntTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtIntTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIntTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIntTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlWis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWis As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblWis control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWis As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWisTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWisTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWisTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWisTemp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCha As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtChaTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChaTemp As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChaTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChaTemp As Global.System.Web.UI.WebControls.Label
End Class
