'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SkillLine

    '''<summary>
    '''chkClassSkill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkClassSkill As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSkillName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkillName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLeftParen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLeftParen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSkillOption control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSkillOption As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRightParen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRightParen As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUntrained control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUntrained As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAbility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbility As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblArmorCheck control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblArmorCheck As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSkillMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSkillMod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblAbilityMod control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAbilityMod As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRanks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRanks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMisc As Global.System.Web.UI.WebControls.TextBox
End Class
