'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Saves

    '''<summary>
    '''lblFortSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFortSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFortBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFortBase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblConSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblConSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMagicModFort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMagicModFort As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMiscModFort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiscModFort As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTempModFort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempModFort As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblRefSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRefSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtRefBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRefBase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblDexSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDexSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMagicModRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMagicModRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMiscModRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiscModRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTempModRef control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempModRef As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWillSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWillSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWillBase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWillBase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblWisSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblWisSave As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMagicModWill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMagicModWill As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMiscModWill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMiscModWill As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtTempModWill control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTempModWill As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBaseAttack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBaseAttack As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtSpellResist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSpellResist As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblGrapple control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrapple As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrappleBaseAttack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrappleBaseAttack As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrappleStr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrappleStr As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblGrappleSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGrappleSize As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGrappleMisc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrappleMisc As Global.System.Web.UI.WebControls.TextBox
End Class
