'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CardsDefault

    '''<summary>
    '''uctrlPitchStats control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPitchStats As Global.leightoneash.PitchStatisticsFull

    '''<summary>
    '''uctrlPitchRankings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPitchRankings As Global.leightoneash.PitchRankingsFull

    '''<summary>
    '''uctrlPitchScoresheet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlPitchScoresheet As Global.leightoneash.PitchScoresheet

    '''<summary>
    '''uctrlCostabiRankings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uctrlCostabiRankings As Global.leightoneash.CostabiRankingsFull
End Class
