'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Standings

    '''<summary>
    '''repNFCN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repNFCN As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repNFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repNFCS As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repNFCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repNFCE As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repNFCW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repNFCW As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repAFCN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repAFCN As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repAFCS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repAFCS As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repAFCE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repAFCE As Global.System.Web.UI.WebControls.Repeater

    '''<summary>
    '''repAFCW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repAFCW As Global.System.Web.UI.WebControls.Repeater
End Class
