'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PitchStatisticsFull

    '''<summary>
    '''ddlPlayers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPlayers As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''ddlSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSize As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnStatistics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnStatistics As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''upGraphs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upGraphs As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''chtTeammates4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chtTeammates4 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''chtTeammates6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chtTeammates6 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''chtOpponents4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chtOpponents4 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''chtOpponents6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chtOpponents6 As Global.System.Web.UI.DataVisualization.Charting.Chart

    '''<summary>
    '''chtPitchRankings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chtPitchRankings As Global.System.Web.UI.DataVisualization.Charting.Chart
End Class
