'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Costabi

    '''<summary>
    '''txtPlayer1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlayer1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlayer2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlayer2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlayer3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlayer3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlayer4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlayer4 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPlayer5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlayer5 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''repCostabi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents repCostabi As Global.System.Web.UI.WebControls.Repeater
End Class
